displayThisText(typeof undeclaredVariable)
displayThisText(typeof true)
displayThisText(typeof 93)
displayThisText(typeof 93n)
displayThisText(typeof Symbol())
displayThisText(typeof {})
displayThisText(typeof $)
